server:
  port: 8111

spring:
  jmx:
    default-domain=s: restsocialnetmessages
    unique-names: true
  data:
    mongodb:
      host: 69.163.46.113
      port: 2521
      username: root
      password: sisint122333
      database: socialnetmessages
      authentication-database: SISADMIN
