server:
  port: 8111

spring:
  data:
    mongodb:
#      host: 69.163.46.113
      host: localhost
#      port: 2521
      port: 27017
      username: root
#      password: sisint122333
      database: socialnetmessages
#      authentication-database: SISADMIN
